### ISSUE TITLE
Unable to view Conlangs, returns HTTP Stauts 500

### ISSUE THREAD

**Issue by thuggeryOfishing** [charliedevs/conlang-dictionary#8]
When I try to open a conlang, take for example, Eleventio. It does not open, but instead appears as a HTTP Status 500. However, this is the only issue I have seen so far.
![Screen Shot 2024-07-22 at 1 11 50 AM](https://github.com/user-attachments/assets/805a5e92-7d1b-4b97-aacd-adc6709b64ad)

**Comment by charliedevs** [comment]
Pushed a fix that should allow you to view the language pages again!

I'm currently changing how word definitions work, and unfortunately I broke the current language view by changing the database schema.

I'll try to prioritize separating the dev database from the production one to prevent issues like this in the future (currently they share the same database), but please bear with me in the meantime as the website is in early development!

**Comment by thuggeryOfishing** [comment]
Amazing! 👍
